### PR TITLE
Don't use AuthComponent if it's not already loaded

### PR DESCRIPTION
**Pull request by chrisjohnson**
AuthComponent is causing a segfault when using Queue::add from command line for me. And given that it's not going to return any valid value in the command line anyway, I suggest that we just don't even bother with it if it's not loaded yet

### CODE REVIEW

**Comment by webtechnick** [comment]
Love the changes, just would like to see the logic for checking it the class_exists to after the App::uses call. I'm not sure it will ever be anything other than null in that logic.

**Comment by chrisjohnson** [comment]
Oh I didn't realize that was the case. If that's true then class_exists will probably never return true because it won't be loaded until the classes attempted to be initialized and the auto load function gets called. Which means there's really no Safeway to detect this

**Comment by zeroasterisk** [comment]
you can switch to `App::import()` which actually attempts to load the class, not map it for future loading.

**Comment by chrisjohnson** [comment]
So my actual intention here was to not even try to load the class at all, so really I should remove App::uses entirely and just leave it as

```
if (!class_exists('AuthComponent')) {
    return null;
}
return AuthComponent::user($field);
```

But I'm not sure that jives with the plugin or not, or if it just makes sense for me. My thinking is, if you are using AuthComponent, by the time it gets to this line of code, AuthComponent will have already been loaded. If you aren't using it or if you're running from command line, the class won't be loaded and so the function will return null.

If that doesn't fit well with the plugin feel free to reject, I wouldn't disagree with you. Unless either of you have a better way to approach it? I can make a PR which only has the bug fix for multiple tasks if you want to just merge that one only.

**Comment by chrisjohnson** [comment]
How about this:

```
if (!class_exists('AppModel')) {
    App::uses('AppModel', 'Queue.Model');
}
class QueueTask extends AppModel {
...
}
```

and then

```
class AppModel {
    public function getCurrentUser() {
        return AuthComponent::user('id');
    }
}
```

And that way I can define getCurrentUser on my own AppModel, and because my own AppModel exists, QueueTask will derive from that AppModel. If my own AppModel doesn't exist, the plugin ships one with a default behavior.

**Comment by chrisjohnson** [comment]
Closing this in favor of a more robust solution I've implemented

**Pull request closed without merging**
